version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - service1   

  # nodeJS services
  api:
    build: .
    ports:
      - 3010:2113
    volumes:
      - .:/usr/src/app
    environment:
        PORT: 2113
        DB_URL: mongodb://mongo_db:27017
        DB_NAME: natalie
    networks:
      - service1   
    depends_on:
      - mongo_db

  sftp:
    image: atmoz/sftp
    ports:
        - "9922:22"
    command: ["foo:pass:::/uploads"]
    networks:
      - turreta_network     
 
networks:
  turreta_network:
    driver: bridge
  service1:

# volume
volumes:
  mongo_db: {}