version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - turreta_network     

  # nodeJS services
  api:
    build: .
    ports:
      - 3010:2113
    volumes:
      - .:/usr/src/app
      - avatars:/usr/src/app/avatars
    environment:
        PORT: 2113
        DB_URL: mongodb://mongo_db:27017
        DB_NAME: natalie
    networks:
      - turreta_network     
    depends_on:
      - mongo_db

networks:
  turreta_network:
    driver: bridge

# volume
volumes:
  mongo_db: {}
  avatars: